import Hashids from 'hashids'

interface Wrestler {
    id: string
    name: string
    nickName: string
    finisherMove: string
    entranceMusic: string
    catchPhrase: string
}

const hasher = new Hashids('hashidsSalt', 4)

export const nickNames = [
    'The 8th Wonder of The World',
    'The 9th Wonder of The World',
    'Above Average',
    'The Ace in The Hole',
    'The Alaskan Assassin',
    'The All-American',
    'The All-American American',
    'The All-American Boy',
    'The Alpha Male',
    'The Mayan Goblin',
    'The Ambling Alp',
    "America's Hardcore Icon",
    "America's Hero",
    'American Angel',
    'American Dragon',
    'The Bull of The Woods',
    'The American Hero',
    'The Anarchist',
    'The Angry Amish Warrior',
    'The Animal',
    'The Anvil',
    'The Asian Nightmare',
    'The Assassin',
    'The Axe',
    'B-Gizzle',
    'The Trailer Park Gangsta',
    'Bad Attitude',
    'The Bad Guy',
    'Bad S',
    'Bamm-Bamm',
    'The Barber',
    'The Barbaric Berzerker',
    'The Bashman',
    'The Reflection of Perfection',
    'The Beast',
    'The Beast from The Black Hole',
    'The Beast from The East',
    'The Next Big Thing',
    'The Beastmaster',
    'The Belfast Bruiser',
    'The Big Cat',
    'Big Daddy',
    'Big Daddy Cool',
    'Big Sexy',
    'Big Lalo',
    'El Presidente',
    'The Big Kahuna',
    'The Big Red Machine',
    'The Big Shot',
    'The Superheavyweight',
    'The Alabama Slamma',
    'Big Thunder',
    'Big Time',
    'The Big Valbowski',
    "The World's Largest Love Machine",
    'The Billion-Dollar Princess',
    'The Bird Man',
    'The Bitchboy Annihilator',
    'The Prince of Perversion',
    'The Black and White Express',
    'Black Magic',
    'The Black Nature Boy',
    'The Black Redneck',
    'The Blonde Bomber',
    'The Blonde Bombshell',
    'The Blueprint',
    'The Body',
    'The Bombshell',
    'The Boogie-Woogie Man',
    'The Boston Bad Boy',
    'The Boston Battler',
    'The Boy Wonder',
    'The Brain',
    'The Brandon Bull',
    'Mr. Wonderful',
    'The Brazilian Beast',
    'The British Babe',
    'British Storm',
    'The Broadstreet Bully',
    'The Brothers of Destruction',
    'Buff Daddy',
    'The Buffalo Bad Boy',
    'The Bull',
    'Bulldog',
    'Bulldozer',
    'The Bullet',
    'The Butcher',
    'The California Hippie',
    'The California Kid',
    'The California Stud',
    'The Calypso Kid',
    "Canada's Greatest Athlete",
    "Canada's Strongest Man",
    'The Canadian Crime Spree',
    'Little Petey Pump',
    'The Canadian Enforcer',
    'The Canadian Freight Train',
    'Captain Charisma',
    'The Canadian Tiger',
    'Captain HUSTLE',
    'Captain Redneck',
    'The Caribbean Legend',
    'The Cat',
    'The Chairman',
    'The Chairman of The Board',
    'The Charismatic Enigma',
    'Choujuu',
    'Classic',
    'The Claw',
    'The Clawmaster',
    'The Coach',
    'The Colossus of Boggo Road',
    'Confederate Currency',
    'Copetes',
    'El Rey Moro',
    'The Cornfed Colossus',
    'The Count of California',
    'Cowboy',
    'The Creation of Devastation',
    'The Crippler',
    'The Croatian Panther',
    'The Cruncher',
    'Cutie Pie',
    "Madonna's Boyfriend",
    'DA MAN',
    'Dangan',
    'Danger Man',
    'Dangerous K',
    'HUSTLE K',
    'Dangerous Queen',
    'The Daredevil of Extreme',
    'Dark Prince',
    'Black Hulk',
    'Das Wunderkind',
    'The Dastardly One',
    'The Danaconda',
    'Deadly Angel',
    'The Definition of Technician',
    'The Demon of The Deep',
    'The Deranged One',
    'The Devious One',
    'Lola Dinamita',
    'The Dirtiest Player in The Game',
    'The Dirty White Boy',
    'The Dirty White Girl',
    'The Diva',
    'Do It To It',
    'Dr. D',
    'Dr. Death',
    'The Dr. of Desire',
    'The Doctor of Style',
    'The Doctor of Thugenomics',
    'The Dogfaced Gremlin',
    'Double A',
    'The Dragon',
    'The Duchess of Dudleyville',
    'The Duke of Dorchester',
    'The Dumpster',
    'East Coast Intensity',
    'The Edge',
    'The Enforcer',
    "Everybody's Favorite Girlfriend",
    "Everybody's Favorite Homeboy",
    'The Extreme Commissioner',
    'The Extreme Giant',
    'The Extreme Strongman',
    'The Extreme Stud',
    'The Sicilian Shooter',
    'The Fabulous Firebird',
    'The Fabulous One',
    'Fear Factor',
    'The Female Fighting Phenom',
    'The First Lady of Hardcore',
    'Flash',
    'The Flatliner',
    'Foxy Lady',
    'The Experience',
    'The Franchise',
    'The Free Spirit',
    'Freight Train',
    'The French Phenom',
    'The Funker',
    'Fuun Noboriryu',
    'The Future',
    'The Gangster of Love',
    'Gato',
    'Genesis',
    'The Savior',
    'The Gentleman',
    'The German Beef',
    'The Giant',
    'The Giant-Killer',
    'The Gigolo',
    'The Gladiator',
    'The Glamazon',
    'Go Time',
    'The Goddess',
    'The Godfather',
    'The Godfather of Extreme',
    'The Gold Standard',
    'The Golden Boy',
    'The Golden Greek',
    'The Golden-Haired Fox',
    'The Golden Warrior',
    "Good Ol' JR",
    'The Greek Goddess',
    'The Green Goddess',
    'The Grim Reaper',
    'The Man from The Dark Side',
    'The Phenom',
    'The Pale Destroyer',
    'The Lord of Darkness',
    'The American Badass',
    'The Guiding Light',
    'Gusano',
    'Hacksaw',
    'The Haitian Sensation',
    'The Hammer',
    'The Handsome Half-Breed',
    'Hard Rock',
    'The Hardcore Chair-Swinging Freaks',
    'The Hardcore Giant',
    'The Hardcore Icon',
    'The Hardcore Legend',
    'The Hardcore Monster',
    'Hardwork',
    'The Head Cheerleader',
    'The Queen of Extreme',
    'The Show Stopper',
    'Heavy Metal',
    'The Heavy Metal Maniac',
    'The Hebrew Hercules',
    'The Helsinki Hellraiser',
    'High IQ',
    'Hinotama Kozou',
    'The Hip Hop Hippo',
    'The Hippest Cat in The Land',
    'The Hitman',
    'Hollywood',
    'Honoo no Hiryu',
    'The Horny Little She-Devil',
    'Hot Chocolate',
    'Hot Stuff',
    'Hotrod',
    'The Rowdy Scot',
    'Hott Stuff',
    'The Houdini of Hardcore',
    'The Immortal One',
    'The Human Highlight Reel',
    'The Human Orchid',
    'The Toast of The Coast',
    'The Sensation of The Nation',
    'The Human Rulebook',
    'The Human Skyscraper',
    'The Human Suplex Machine',
    'The Path of Rage',
    'The Orange and Black Attack',
    'The One Man Human Crime Spree',
    'The Human Wrecking Machine',
    'Hurricane',
    'Hustle Prince',
    'The Iceman',
    'The Ideal Reflection',
    'The Idol',
    'Inazuma Senshi',
    'The Innovator of Offense',
    'The Innovator of Violence',
    'The Insane Luchador',
    'The Internet Icon',
    'Iron Man',
    'Ironhead',
    'Ironman',
    'The Italian Eagle',
    'The Italian Monster',
    'The Italian Superman',
    'Jam',
    "Jammin'",
    'The Japanese Buzzsaw',
    'Jefe Indio Dedos Chuecos',
    'The Jezebel',
    'The Joeverine',
    'Juan El Hermoso',
    'The Juice',
    'K-Dog',
    'Kakumei Senshi',
    'Kamen Kizoku',
    'Kanaami no Oni',
    'The Kansas Cowboy',
    'The King',
    'King Kong',
    'The King of Chaos',
    'The King of Old School',
    'The Korean Monster',
    'Kryptonite',
    'La Bestia del Apocalipsis',
    'La Bruja',
    'La Calabacita',
    'La Pantera Rosa',
    'The Latin Heartthrob',
    'The Latina Sensation',
    'The Latina Super Woman',
    'Latino Heat',
    'The Laughing Man',
    'The Legacy',
    'The Legend-Killer',
    'The Lethal One',
    'Black Machismo',
    'The Lethal Weapon',
    'Lightning',
    'Lightning Foot',
    'The Living Legend',
    'Lone Eagle',
    'Rey Águila',
    'Lonestar',
    'The Loose Cannon',
    'The Rogue Horseman',
    'The Ticking Time Bomb',
    'The Louisville Slugger',
    'The Louisville Lip',
    'Los Sustos',
    'The Love Machine',
    'Loverboy',
    'The Macdaddies of Violence',
    'The Macho Man',
    'The Machine Gun',
    'Mad Dog',
    'The Mad Dogs of War',
    'Made in Poland',
    'The Madman from The Badlands',
    'The Madman from The Sudan',
    'Magnificent',
    'The Rock',
    'The Main Attraction',
    'The Main Event',
    'Custom Chucky P',
    'The Main Man',
    'The Man',
    'The Man-Bear',
    'The Man of 1000 Holds',
    'The Manager of Champions',
    'The Masterpiece',
    'The Mastodon',
    'Mean Streak',
    'The Messiah of The Backbreaker',
    'The Messiah of The Spinebuster',
    'The Mexican Superman',
    'SuperMex',
    'The Miami Pound Machine',
    'The Turncoat',
    'The Rod Damn Champ',
    'The Milkman',
    'The Million Dollar Man',
    'The Mind',
    'Mississippi Queen',
    'The Missouri Tiger',
    'Mr. 200%',
    'Mr. 630',
    'Mr. America',
    'Mr. Ass',
    'The One',
    'Mr. Charisma',
    'No Gimmick Needed',
    'Hard Knox',
    'Mr. Chippendale',
    'Mr. Fantasy',
    'Mr. Class',
    'Mr. Danger',
    'Mr. Ebony',
    'Mr. Electricity',
    'Mr. Hardcore',
    'Mr. Irresistible',
    'Mr. Magnificent',
    'Mr. Perfect',
    'Mr. Piledriver',
    'Mr. Ratings',
    'Mr. Romeo',
    'Dirty Deeds',
    'Mr. Smackdown',
    'Mr. Torture',
    'Mr. TV',
    'Mr. USA',
    'The Mistress of Mayhem',
    'The Miz',
    'Moalm',
    'The Model',
    'The Modern Day Miracle',
    'Moeru Toukon',
    'Mongo',
    'The Monster',
    'Monster K',
    'The Mormon Giant',
    'The Moscow Mauler',
    'Mourningstar',
    'The Mouth of The South',
    'Namida no Karisuma',
    'The Narcissist',
    'The Natural',
    'The Natural One',
    'The Nature Boy',
    'The New Era Icon',
    "The New F'N Show",
    'The New Thing',
    'The Technical Messiah',
    'The Next Big Thing',
    'No Class',
    'The Noticeable One',
    'The Dandy Highwayman',
    'The Notorious 187',
    'The Notorious B.I.G.',
    'The Notorious K.I.D.',
    'Number One',
    'The Italian Stallion',
    'The Omega',
    'The One Man Gang',
    'Hands of Stone',
    'The Orange Dream',
    'The Original Gangsta',
    'The Original King of Swing',
    'The Other Dark Meat',
    'Outlaw',
    'The Palm Beach Heartthrob',
    'The Paragon of Virtue',
    'The Pascagoula Plowboy',
    'The Pearl of The Orient',
    'The Pearl River Powerhouse',
    'The Brahma Bull',
    'The Perfect 10',
    'The Perfect One',
    'Perfectshawn',
    'The Mecca of Manhood',
    'The Phenomenal One',
    'The Pink and Black Attack',
    'The Pit Bull',
    'Pitbull',
    'The Pinnacle',
    'The Playboy',
    'The Polar Bear',
    'The Policy',
    'Polish Power',
    'The Polish Prince',
    'The Polynesian Warrior',
    'Ponzoña',
    'The Portuguese Man-Of-War',
    'The Predator',
    'Pretty Boy',
    'Primetime',
    'The Prince of Passion',
    'The Prince of Pranks',
    'The Prince of Punk',
    'The Reject',
    'The Princess of Darkness',
    'The Prize',
    'The Prodigy',
    'The Professor',
    'The Profile',
    'The Blond Adonis',
    'The Pug',
    'The Punisher',
    'The Punjabi Nightmare',
    'The Quintessential Studmuffin',
    'The Rabid Wolverine',
    'The Human Buzzsaw',
    "The Ragin' Bull",
    "The Ragin' Cajun",
    'The Rapmaster',
    'The Rate Tank',
    'The Rated R Superstar',
    'The Ravishing One',
    'Rayo Mexicano',
    'The Real Deal',
    'The Real Double J',
    'Road Dogg',
    'The Red and Black Attack',
    'Redd Dogg',
    'The Redneck Messiah',
    'Redneck Woman',
    'Rock N Roll',
    'Rock Star',
    'The Rocket',
    'Rodzilla',
    'The Rogue Outsider',
    'The Straight Edge Warrior',
    'The Role Model',
    'Rollerball',
    'The Rookie Monster',
    "The Big F'N Deal",
    'The Man-Beast',
    'The War Machine',
    'The Royal Stud',
    'The Ruffneck',
    'The Russian Bear',
    'The Russian Giant',
    'The Russian Lion',
    'The Russian Nightmare',
    'Russian Sickle',
    'The St. Louis Woman',
    'The Samoan Bulldozer',
    'The Samoan Storm',
    'The Samoan Submission Machine',
    "San Antonio's Original Vato Loco",
    "Satan's Cheerleader",
    'Scrap Iron',
    'The Scrub',
    'The Sensation of Innovation',
    'The Show',
    'The Suicide Bomb',
    'Sugar',
    'IBM: Insane Bump Machine',
    'The Sensei',
    'The Sensei of Mattitude',
    'The Sexiest Man on Earth',
    'Sexual Chocolate',
    'The King of The Jungle',
    'The Shah',
    'The Dog',
    'The Shaman of Sexy',
    'The Guru of Greatness',
    'The Tuesday Night Delight',
    'The Shooter',
    'Showtime',
    'The Paranoid Pied Piper of TNA',
    'The Silence Behind The Violence',
    'The Silencer',
    'The Silver-Tongued Pugilist',
    'The Silverback',
    'Simply Irresistible',
    'Double-J',
    'The Chosen One',
    'The King of The Mountain',
    'Simply Sensational',
    'The Snowman',
    'The Crown Prince of Hardcore',
    "Smackdown's #1 Announcer",
    'The Snake',
    'Soulman',
    'The Soviet Terror',
    'Sparkplug',
    'Special Delivery',
    'Special K',
    'The Sports Illustrated Legend',
    'Stampede Kid',
    'Stinger',
    'The Icon',
    'Straight Up',
    'The Sultan of Swing',
    'Super Estrella',
    'Superbrat',
    'Superfan',
    'Superfly',
    'Superman from Space',
    'Supermouth',
    'Supersock',
    'Superstar',
    'The Supreme Fighting Machine',
    'The Sweet Music Man',
    'The Swordsman',
    'TNT',
    'The Tennessee Cowboy',
    'The Tennessee Stud',
    'Tetsu no Tsume',
    'Tetsujin',
    'Johnny Texas',
    'Juan El Texano',
    'The Texas Cowgirl',
    'The Texas Rattlesnake',
    'The Bionic Redneck',
    "This Year's Model",
    'The Thrillseeker',
    'Tiger Dream',
    'The Timekeeper',
    'To-chan',
    'Too Hot',
    'Too Sexy',
    'The Total Athlete',
    'The Total Package',
    'Touyou no Kyojin',
    'The Train',
    'The Trend Setter',
    'Book Daddy',
    'The Truth',
    'Turbo Lover',
    'The Ultimate Temptation',
    'The Ultimate Warrior',
    'The Underwear Model',
    'The Unholy Altar Boy',
    'The Universal Heartthrob',
    'The Urban Legend',
    'The Vampire',
    'The King of Men',
    'The Hollywood Fashion Plate',
    'The Ayatollah',
    'The Voice of ECW',
    'The Voodoo Queen',
    'The Hardcore Knockout',
    'Waka Daisho',
    'The Walking Condominium',
    "The Walkin' Riot",
    'The War Eagle',
    'The Weasel',
    'The White Angel',
    'White Lightning',
    'White Thunder',
    'Big Poppa Pump',
    'The Big Bad Booty Daddy',
    'Freakzilla',
    'The Genetic Freak',
    'The Widowmaker',
    'The Stalker',
    'The Wildcat',
    'Wildfire',
    'The Big Don',
    'The Winner',
    'Mr. Technical',
    "The World's Most Dangerous Man",
    "The World's Strongest Man",
    'The Worm',
    'The Z-Man'
]

const usNames = [
    { name: 'James', rank: 1 },
    { name: 'Robert', rank: 2 },
    { name: 'John', rank: 3 },
    { name: 'Michael', rank: 4 },
    { name: 'David', rank: 5 },
    { name: 'William', rank: 6 },
    { name: 'Richard', rank: 7 },
    { name: 'Joseph', rank: 8 },
    { name: 'Thomas', rank: 9 },
    { name: 'Christopher', rank: 10 },
    { name: 'Charles', rank: 11 },
    { name: 'Daniel', rank: 12 },
    { name: 'Matthew', rank: 13 },
    { name: 'Anthony', rank: 14 },
    { name: 'Mark', rank: 15 },
    { name: 'Donald', rank: 16 },
    { name: 'Steven', rank: 17 },
    { name: 'Andrew', rank: 18 },
    { name: 'Paul', rank: 19 },
    { name: 'Joshua', rank: 20 },
    { name: 'Kenneth', rank: 21 },
    { name: 'Kevin', rank: 22 },
    { name: 'Brian', rank: 23 },
    { name: 'George', rank: 24 },
    { name: 'Timothy', rank: 25 },
    { name: 'Ronald', rank: 26 },
    { name: 'Jason', rank: 27 },
    { name: 'Edward', rank: 28 },
    { name: 'Jeffrey', rank: 29 },
    { name: 'Ryan', rank: 30 },
    { name: 'Jacob', rank: 31 },
    { name: 'Gary', rank: 32 },
    { name: 'Nicholas', rank: 33 },
    { name: 'Eric', rank: 34 },
    { name: 'Jonathan', rank: 35 },
    { name: 'Stephen', rank: 36 },
    { name: 'Larry', rank: 37 },
    { name: 'Justin', rank: 38 },
    { name: 'Scott', rank: 39 },
    { name: 'Brandon', rank: 40 }
]

const surNames = [
    { name: 'Smith', rank: 1 },
    { name: 'Johnson', rank: 2 },
    { name: 'Williams', rank: 3 },
    { name: 'Brown', rank: 4 },
    { name: 'Jones', rank: 5 },
    { name: 'Miller', rank: 6 },
    { name: 'Davis', rank: 7 },
    { name: 'Garcia', rank: 8 },
    { name: 'Rodriguez', rank: 9 },
    { name: 'Martinez', rank: 10 },
    { name: 'Hernandez', rank: 11 },
    { name: 'Lopez', rank: 12 },
    { name: 'Gonzalez', rank: 13 },
    { name: 'Perez', rank: 14 },
    { name: 'Taylor', rank: 15 },
    { name: 'Anderson', rank: 16 },
    { name: 'Wilson', rank: 17 },
    { name: 'Jackson', rank: 18 },
    { name: 'Moore', rank: 19 },
    { name: 'Martin', rank: 20 },
    { name: 'Lee', rank: 21 },
    { name: 'Lewis', rank: 22 },
    { name: 'Walker', rank: 23 },
    { name: 'Hall', rank: 24 },
    { name: 'Allen', rank: 25 },
    { name: 'Young', rank: 26 },
    { name: 'King', rank: 27 },
    { name: 'Wright', rank: 28 },
    { name: 'Scott', rank: 29 },
    { name: 'Green', rank: 30 },
    { name: 'Baker', rank: 31 },
    { name: 'Adams', rank: 32 },
    { name: 'Nelson', rank: 33 },
    { name: 'Carter', rank: 34 },
    { name: 'Mitchell', rank: 35 },
    { name: 'Perez', rank: 36 },
    { name: 'Roberts', rank: 37 },
    { name: 'Turner', rank: 38 },
    { name: 'Phillips', rank: 39 },
    { name: 'Campbell', rank: 40 },
    { name: 'Parker', rank: 41 },
    { name: 'Evans', rank: 42 },
    { name: 'Edwards', rank: 43 },
    { name: 'Collins', rank: 44 },
    { name: 'Stewart', rank: 45 },
    { name: 'Sanchez', rank: 46 },
    { name: 'Morris', rank: 47 },
    { name: 'Rogers', rank: 48 },
    { name: 'Reed', rank: 49 },
    { name: 'Cook', rank: 50 }
]

export const moves = [
    '450° splash',
    '630° senton',
    'Aided brainbuster',
    'Aided headscissors takedown',
    'Aided leapfrog body guillotine',
    'Aided neckbreaker',
    'Aided piledriver',
    'Aided powerbomb',
    'Aided splash',
    'Aided superbomb',
    'Aided suplex',
    'Aided wheelbarrow facebuster',
    'Aided wheelbarrow suplex',
    'Aided whiplash',
    'Argentine rack neckbreaker combination',
    'Arm twist ropewalk chop',
    'Asian mist',
    'Assisted senton',
    'Avalanche frankensteiner',
    'Axe handle elbow drop',
    'Back elbow',
    'Back fist',
    'Back kick',
    'Backbreaker hold diving attack combination',
    'Backbreaker hold diving elbow drop combination',
    'Backbreaker hold top-rope legdrop combination',
    'Backflip kick',
    'Backhand chop',
    'Battering ram',
    'Bearhug hold attack combination',
    'Bearhug hold flying crossbody combination',
    'Bearhug hold high kick combination',
    'Bearhug hold seated senton combination',
    'Bearhug hold superkick jackknife pin combination',
    'Bearhug hold top-rope legdrop combination',
    'Belly to back suplex neckbreaker combination',
    'Bicycle kick',
    'Big boot',
    'Big splash',
    'Bionic elbow',
    'Biting',
    'Body avalanche',
    'Bronco buster',
    'Butt drop',
    'Cactus clothesline',
    'Calf kick',
    'Cannonball',
    'Catching hip toss',
    'Chair shot',
    'Chair thrust',
    'Chop block',
    'Chop drop',
    'Corkscrew elbow drop',
    'Corner back elbow',
    'Corner backflip kick',
    'Corner clothesline',
    'corner slingshot splash',
    'Crane kick',
    'Crooked arm lariat',
    'Cross chop',
    'Crossbody',
    'Death Drop',
    'Diamond dust',
    'Discus back elbow',
    'Discus elbow smash',
    'Discus',
    'Diving back elbow drop',
    'Diving bulldog',
    'Diving crossbody',
    'Diving DDT',
    'Diving double axe handle',
    'Diving elbow drop',
    'Diving fist drop',
    'Diving headbutt low blow',
    'Diving headbutt',
    'Diving hurricanrana',
    'Diving knee drop',
    'Diving leg drop bulldog',
    'Diving leg drop low blow',
    'Diving leg drop',
    'Diving shoulder block',
    'Diving spear',
    'Diving stomp',
    'Doomsday Device',
    'Double Axe Hammer',
    'Double axe handle',
    'Double belly to back suplex',
    'Double bulldog',
    'Double butt splash',
    'Double chokeslam',
    'Double clothesline',
    'Double crucifix powerbomb',
    'Double cutter',
    'Double DDT',
    'Double drop toe-hold',
    'Double dropkick',
    'Double elbow drop',
    'Double enzuigiri',
    'Double extreme leg drop',
    'Double facebuster',
    "Double fireman's carry",
    'Double flapjack',
    'Double foot stomp',
    'Double hip toss',
    'Double inverted DDT',
    'Double knee lift',
    'Double knee',
    'Double lifting DDT',
    'Double missile dropkick',
    'Double slap',
    'Double Sledge',
    'Double STO',
    'Double submission',
    'Double superkick',
    'Double suplex',
    'Dragon whip',
    'Dragonrana',
    'Dropkick',
    'Elbow drop',
    'Elbow smash',
    'Elevated jawbreaker',
    'Elevated splash',
    'Enzuigiri',
    'European uppercut',
    'Eye poke',
    'Eye rake',
    'Facewash',
    'Fireball',
    'Fist drop',
    'Flapjack DDT',
    'Flying calf kick',
    'Flying clothesline',
    'Flying forearm smash',
    'Flying lariat',
    'Flying neckbreaker',
    'Flying spinning heel kick',
    'Flying thrust kick',
    'Football kick',
    'Forearm club',
    'Forearm drop',
    'Forearm smash',
    'Forehand chop',
    'Frankensteiner',
    'Frog splash',
    'German U-Turn',
    'Go 2 Sleep',
    'Gory bomb cutter combination',
    'Guitar shot',
    'Hair pull',
    'Handspring',
    'Hangman',
    'Hart Attack',
    'Headbutt drop',
    'Headbutt',
    'Heart Punch',
    'High knee',
    'High-angle senton bomb',
    'Hip attack',
    'Hiptoss Aided hiptoss combination',
    'Imploding 450° splash',
    'Imploding senton bomb',
    'Jumping high kick',
    'Kesagiri chop',
    'Kick',
    'Knee drop bulldog',
    'Knee drop',
    'Knee lift',
    'Knee strikes',
    'Koronco buster',
    'Lariat running chop block combination',
    'Lariat takedown',
    'Leapfrog body guillotine',
    'Leg drop splash combination',
    'Leg drop',
    'Leg lariat',
    'Legsweep',
    'Lou Thesz press',
    'Low blow',
    'Molly-Go-Round',
    'Mongolian chop',
    'Moonsault double foot stomp',
    'Moonsault leg drop',
    'Moonsault senton',
    'Moonsault',
    'Mounted elbow drop',
    'Mounted punches',
    'Mule kick',
    'Mushroom stomp',
    'One-man con-chair-to',
    'Overhead chop',
    'Overhead kick',
    'Palm strike',
    'Pendulum',
    'Pheonixrana',
    'Phoenix splash',
    'Poetry in Motion',
    'Polish Hammer',
    'Power-Plex',
    'Powerbomb diving attack combination',
    'Powerbomb diving legdrop combination',
    'Powerbomb double knee backbreaker combination',
    'Powerbomb flying neckbreaker combination',
    'Powerbomb missile dropkick combination',
    'Powerbomb neckbreaker combination',
    'Powerbomb shiranui combination',
    'Powerbomb suplex combination',
    'Punt',
    'Rebound clothesline',
    'Reverse frankensteiner',
    'Reverse hangman',
    'Rocket Launcher',
    'Rolling Thunder',
    'Rolling wheel kick',
    'Russian legsweep clothesline combination',
    'Samoan drop neckbreaker combination',
    'Savate kick',
    'Scissors kick',
    'Scoop powerslam Powerbomb combination',
    'Seated senton',
    'Senton bomb',
    'Senton',
    'Shining Wizard',
    'Shiranui',
    'Shoot kick',
    'Shooting star DDT',
    'Shooting star elbow drop',
    'Shooting star leg drop',
    'Shooting star press',
    'Shooting star senton',
    'Shooting star',
    'Short-arm clothesline',
    'Short-arm elbow smash',
    'Sidewalk slam top-rope legdrop combination',
    'Sky lift slam',
    'Sliding forearm smash',
    'Slingshot catapult clothesline combination',
    'Slingshot catapult missile dropkick combination',
    'Slingshot catapult top rope bulldog combination',
    'Sole kick',
    'Somersault leg drop',
    'Spanish fly',
    'Spear',
    'Spin kick',
    'Spinning back fist',
    'Spinning headlock elbow drop',
    'Spinning heel kick',
    'Spinning knee',
    'Splash',
    'Springboard bulldog',
    'Springboard clothesline',
    'Stack-superplex',
    'Standing moonsault',
    'Standing shooting star press',
    'Stinger splash',
    'Stink Face',
    'STO big boot combination',
    'STO Russian legsweep combination',
    'Stomp',
    'Striking spear',
    'Sunset flip',
    'Superkick spinning leg sweep combination',
    'Superkick-Plex',
    'Superkick',
    'Suplex flying attack combination',
    'Testicular claw',
    'Three-point stance clothesline',
    'Throat thrust',
    'Tiger feint kick',
    'Tilt-a-whirl crossbody',
    'Toe kick',
    'Total Elimination',
    'Trapping headbutts',
    'Turnbuckle thrust',
    'Uppercut',
    'Vertical press',
    'Wheelbarrow facebuster cutter combination',
    'Wheelbarrow hold top rope legdrop combination',
    'Wind-up punch',
    'Wishbone'
]

const prases = [
    'You Will Serve Hard Time',
    "I'm the Boogey Man and I'm Comin to Getcha",
    'Can You Dig It Sucka',
    'The Best There Is the Best There Was and the Best There Ever Will Be',
    'Bang Bang',
    'Thats Cool/ Thats Not Cool',
    'I Am the Best in the World at What I Do',
    'I Am the Ayatollah of Rocck N Rolla',
    'Welcome to Raw Is Jericho',
    'This Is for All My Peeps',
    "Straight Edge Means I'm Drug Free, Alcohol Free and Better Than You",
    'I Am the Best in the World',
    'Sooner or Later Everyone Taps',
    'Its Me Its Me Its DDP',
    'Im Dolph Ziggler',
    'Owww Have Mercy',
    'Suck It',
    'For the Benefit of Those with Flash Photography...',
    'Viva La Raza',
    'If Youre Not Cheating Youre Not Trying',
    'Get on Board the Ho Train',
    "Pimpin Ain't Easy",
    'Whos Next',
    'You Will Never Forget the Name Golddust',
    'Whatcha Gonna Do When Hulkamania Runs Wild on You',
    'Say Your Prayers and Eat Your Vitamins',
    'I Am a Wrestling God',
    'J E Double F J A Double R E Double T Thats Double J Jeff Jarrett',
    'The Pleasure Was All Yours',
    'Hey There Tough Guy',
    'USA USA Hooooo!',
    'Stompin a Mud Hole and Walkin It Dry',
    'This Is One Hell of a Slobberknocker',
    'The Champ Is Here',
    'Hustle Loyalty Respect',
    'I Am the Shaman of Sexy',
    "Its True Its Damn True/It's Real It's Damn Real",
    'I Dont Suck, You Suck',
    'What a Rush',
    'Simply Flawless',
    'Here Comes the Pain',
    'Have a Nice Day',
    'Welcome to the Hall of Pain',
    'I Will Not Die',
    'I Am the Most Genetically Jacked Athletically Stacked Giant Walking Today',
    'I Am the DNA of TNA',
    'Can I Have Your Attention Please',
    'Im Awesome',
    'Kennedy...kennedy/ Anderson...anderson',
    'Simply Perfect',
    'Big Things Poppin Little Things Stoppin',
    "When You're NWO You're NWO for Life",
    'Oh You Didnt Know, Your Ass Better Call Somebody',
    'Youre Either Nexus or Against Us',
    'I Am Not a Nugget',
    'Whats Up/shut Up',
    'I Am the Legend Killer',
    'Quote the Raven Nevermore',
    'Say Hello to the Bad Guy',
    'Wooooo!',
    'To Be the Man You Gotta Beat the Man',
    'Im a Kiss Stealing, Wheeling Dealing, Limousine Riding, Jet Flyng Son of a Gun',
    'Space Mountain May Be the Oldest Ride in the Park, but It Has the Longest Line',
    'All the Women Want to Be with Me, and the Men Want to Be Like Me',
    'Know Your Role and Shut Your Mouth',
    'Im Gonna Lay the Smackdown on Your Candy Ass',
    'Can You Smell What the Rock Is Cookin',
    'Finally the Rock Has Come Back to (Whatever City He Is In)',
    'It Doesnt Matter',
    'Just Bring It',
    'Everybody Pays the Piper',
    'Just When They Think They Know the Answers I Change the Questions',
    'Damn!',
    "Im the Whole F'n Show",
    'Woo Woo Woo You Know It',
    'This Is for All the Ladies Who Wanna Be Me and All the Men Who Come to See Me',
    'Big Poppa Pumps Your Hook-Up, Holla If You Hear Me',
    'Thats an Order',
    'The Heart Break Kid Has Left the Building',
    'Listen Fella!',
    'Its Showtime',
    'If You Wanna See Me Whoop His Ass Give Me a Hell Yeah',
    'Austin 3:16 Says I Just Whooped Your Ass',
    'What?',
    'Beat Me If You Can... Survive If I Let You!',
    'D-Von, Get the Tables!',
    'Everyones Got a Price',
    'Holla Playa',
    'Its Time to Play the Game',
    'Cause Im That Damn Good',
    'Feel the Power',
    'Rest in Peace',
    'Ill Make Ya Famous',
    'Its Time, Its Vader Time',
    'Hello Ladies',
    'Excuse Me',
    'Youre Fired',
    'Kiss My Ass',
    'You Screwed Bret',
    'This Is Awesome'
]

const songs = [
    {
        rank: 1,
        title: 'Like a Rolling Stone',
        artist: 'Bob Dylan',
        album: 'Highway 61 Revisited',
        year: '1965'
    },
    {
        rank: 2,
        title: "(I Can't Get No) Satisfaction",
        artist: 'The Rolling Stones',
        album: 'Out of Our Heads',
        year: '1965'
    },
    {
        rank: 3,
        title: 'Imagine',
        artist: 'John Lennon',
        album: 'Imagine',
        year: '1971'
    },
    {
        rank: 4,
        title: "What's Going On",
        artist: 'Marvin Gaye',
        album: "What's Going On",
        year: '1971'
    },
    {
        rank: 5,
        title: 'Respect',
        artist: 'Aretha Franklin',
        album: 'I Never Loved a Man the Way I Love You',
        year: '1967'
    },
    {
        rank: 6,
        title: 'Good Vibrations',
        artist: 'The Beach Boys',
        album: 'Smiley Smile/Wild Honey',
        year: '1966'
    },
    {
        rank: 7,
        title: 'Johnny B. Goode',
        artist: 'Chuck Berry',
        album: 'The Anthology',
        year: '1958'
    },
    {
        rank: 8,
        title: 'Hey Jude',
        artist: 'The Beatles',
        album: 'Hey Jude',
        year: '1968'
    },
    {
        rank: 9,
        title: 'Smells Like Teen Spirit',
        artist: 'Nirvana',
        album: 'Nevermind',
        year: '1991'
    },
    {
        rank: 10,
        title: "What'd I Say",
        artist: 'Ray Charles',
        album: "What'd I Say",
        year: '1959'
    },
    {
        rank: 11,
        title: 'My Generation',
        artist: 'The Who',
        album: 'My Generation',
        year: '1965'
    },
    {
        rank: 12,
        title: 'A Change Is Gonna Come',
        artist: 'Sam Cooke',
        album: 'Portrait of a Legend 1951-1964',
        year: '1964'
    },
    {
        rank: 13,
        title: 'Yesterday',
        artist: 'The Beatles',
        album: 'Help!',
        year: '1965'
    },
    {
        rank: 14,
        title: "Blowin' in the Wind",
        artist: 'Bob Dylan',
        album: "The Freewheelin' Bob Dylan",
        year: '1963'
    },
    {
        rank: 15,
        title: 'London Calling',
        artist: 'The Clash',
        album: 'London Calling',
        year: '1980'
    },
    {
        rank: 16,
        title: 'I Want to Hold Your Hand',
        artist: 'The Beatles',
        album: 'Meet the Beatles!',
        year: '1963'
    },
    {
        rank: 17,
        title: 'Purple Haze',
        artist: 'The Jimi Hendrix Experience',
        album: 'Are You Experienced?',
        year: '1967'
    },
    {
        rank: 18,
        title: 'Maybellene',
        artist: 'Chuck Berry',
        album: 'The Anthology',
        year: '1955'
    },
    {
        rank: 19,
        title: 'Hound Dog',
        artist: 'Elvis Presley',
        album: ' Elvis 30 #1 Hits',
        year: '1956'
    },
    {
        rank: 20,
        title: 'Let It Be',
        artist: 'The Beatles',
        album: 'Let It Be',
        year: '1970'
    },
    {
        rank: 21,
        title: 'Born to Run',
        artist: 'Bruce Springsteen',
        album: 'Born to Run',
        year: '1975'
    },
    {
        rank: 22,
        title: 'Be My Baby',
        artist: 'The Ronettes',
        album: 'The Best of the Ronettes',
        year: '1963'
    },
    {
        rank: 23,
        title: 'In My Life',
        artist: 'The Beatles',
        album: 'Rubber Soul',
        year: '1965'
    },
    {
        rank: 24,
        title: 'People Get Ready',
        artist: 'The Impressions',
        album: 'The Very Best of the Impressions',
        year: '1965'
    },
    {
        rank: 25,
        title: 'God Only Knows',
        artist: 'The Beach Boys',
        album: 'Pet Sounds',
        year: '1966'
    },
    {
        rank: 26,
        title: "(Sittin' On) The Dock of the Bay",
        artist: 'Otis Redding',
        album: 'The Dock of the Bay',
        year: '1968'
    },
    {
        rank: 27,
        title: 'Layla',
        artist: 'Derek and the Dominos',
        album: 'Layla And Other Assorted Love Songs',
        year: '1970'
    },
    {
        rank: 28,
        title: 'A Day in the Life',
        artist: 'The Beatles',
        album: "Sgt. Pepper's Lonely Hearts Club Band",
        year: '1967'
    },
    {
        rank: 29,
        title: 'Help!',
        artist: 'The Beatles',
        album: 'Help!',
        year: '1965'
    },
    {
        rank: 30,
        title: 'I Walk the Line',
        artist: 'Johnny Cash',
        album: 'The Complete Original Sun Singles',
        year: '1956'
    },
    {
        rank: 31,
        title: 'Stairway to Heaven',
        artist: 'Led Zeppelin',
        album: 'Led Zeppelin IV',
        year: '1971'
    },
    {
        rank: 32,
        title: 'Sympathy for the Devil',
        artist: 'The Rolling Stones',
        album: 'Beggars Banquet',
        year: '1968'
    },
    {
        rank: 33,
        title: 'River Deep - Mountain High',
        artist: 'Ike & Tina Turner',
        album: 'Proud Mary: The Best of Ike and Tina Turner',
        year: '1966'
    },
    {
        rank: 34,
        title: "You've Lost That Lovin' Feelin'",
        artist: 'The Righteous Brothers',
        album: 'Anthology 1962-1974',
        year: '1964'
    },
    {
        rank: 35,
        title: 'Light My Fire',
        artist: 'The Doors',
        album: 'The Doors',
        year: '1967'
    },
    {
        rank: 36,
        title: 'One',
        artist: 'U2',
        album: 'Achtung Baby',
        year: '1991'
    },
    {
        rank: 37,
        title: 'No Woman, No Cry',
        artist: 'Bob Marley & The Wailers',
        album: 'Natty Dread',
        year: '1975'
    },
    {
        rank: 38,
        title: 'Gimme Shelter',
        artist: 'The Rolling Stones',
        album: 'Let It Bleed',
        year: '1969'
    },
    {
        rank: 39,
        title: "That'll Be the Day",
        artist: 'Buddy Holly & The Crickets',
        album: 'Greatest Hits',
        year: '1957'
    },
    {
        rank: 40,
        title: 'Dancing in the Street',
        artist: 'Martha and the Vandellas',
        album: 'The Ultimate Collection',
        year: '1964'
    },
    {
        rank: 41,
        title: 'The Weight',
        artist: 'The Band',
        album: 'Music From Big Pink',
        year: '1968'
    },
    {
        rank: 42,
        title: 'Waterloo Sunset',
        artist: 'The Kinks',
        album: 'Something Else By The Kinks',
        year: '1968'
    },
    {
        rank: 43,
        title: 'Tutti-Frutti',
        artist: 'Little Richard',
        album: 'The Georgia Peach',
        year: '1956'
    },
    {
        rank: 44,
        title: 'Georgia On My Mind',
        artist: 'Ray Charles',
        album: 'Ultimate Hits Collection',
        year: '1960'
    },
    {
        rank: 45,
        title: 'Heartbreak Hotel',
        artist: 'Elvis Presley',
        album: 'Elvis 30 #1 Hits',
        year: '1956'
    },
    {
        rank: 46,
        title: 'Heroes',
        artist: 'David Bowie',
        album: 'Heroes',
        year: '1977'
    },
    {
        rank: 47,
        title: 'All Along the Watchtower',
        artist: 'The Jimi Hendrix Experience',
        album: 'Electric Ladyland',
        year: '1968'
    },
    {
        rank: 48,
        title: 'Bridge Over Troubled Water',
        artist: 'Simon & Garfunkel',
        album: 'Bridge Over Troubled Water',
        year: '1970'
    },
    {
        rank: 49,
        title: 'Hotel California',
        artist: 'Eagles',
        album: 'Hotel California',
        year: '1976'
    },
    {
        rank: 50,
        title: 'The Tracks Of My Tears',
        artist: 'Smokey Robinson and the Miracles',
        album: 'Going to a Go-Go',
        year: '1965'
    },
    {
        rank: 51,
        title: 'The Message',
        artist: 'Grandmaster Flash and the Furious Five',
        album: 'The Best of Sugar Hill Records',
        year: '1980'
    },
    {
        rank: 52,
        title: 'When Doves Cry',
        artist: 'Prince and The Revolution',
        album: 'Purple Rain',
        year: '1984'
    },
    {
        rank: 53,
        title: 'When A Man Loves A Woman',
        artist: 'Percy Sledge',
        album: 'It Tears Me Up: The Best of Percy Sledge',
        year: '1966'
    },
    {
        rank: 54,
        title: 'Louie Louie',
        artist: 'The Kingsmen',
        album: 'The Best of the Kingsmen',
        year: '1963'
    },
    {
        rank: 55,
        title: 'Long Tall Sally',
        artist: 'Little Richard',
        album: 'The Georgia Peach',
        year: '1956'
    },
    {
        rank: 56,
        title: 'Anarchy in the U.K.',
        artist: 'Sex Pistols',
        album: "Never Mind the Bollocks, Here's the Sex Pistols",
        year: '1976'
    },
    {
        rank: 57,
        title: 'A Whiter Shade of Pale',
        artist: 'Procol Harum',
        album: 'Greatest Hits',
        year: '1967'
    },
    {
        rank: 58,
        title: 'Billie Jean',
        artist: 'Michael Jackson',
        album: 'Thriller',
        year: '1983'
    },
    {
        rank: 59,
        title: "The Times They Are a-Changin'",
        artist: 'Bob Dylan',
        album: "The Times They Are A-Changin'",
        year: '1964'
    },
    {
        rank: 60,
        title: "Let's Stay Together",
        artist: 'Al Green',
        album: "Let's Stay Together",
        year: '1971'
    },
    {
        rank: 61,
        title: "Whole Lotta Shakin' Going On",
        artist: 'Jerry Lee Lewis',
        album: 'Original Sun Greatest Hits',
        year: '1957'
    },
    {
        rank: 62,
        title: 'Bo Diddley',
        artist: 'Bo Diddley',
        album: 'His Best: The Chess 50th Anniversary Collection',
        year: '1955'
    },
    {
        rank: 63,
        title: "For What It's Worth",
        artist: 'Buffalo Springfield',
        album: 'Buffalo Springfield',
        year: '1967'
    },
    {
        rank: 64,
        title: 'She Loves You',
        artist: 'The Beatles',
        album: 'The Beatles 1',
        year: '1963'
    },
    {
        rank: 65,
        title: 'Sunshine of Your Love',
        artist: 'Cream',
        album: 'Disraeli Gears',
        year: '1968'
    },
    {
        rank: 66,
        title: 'Redemption Song',
        artist: 'Bob Marley & The Wailers',
        album: 'Uprising',
        year: '1980'
    },
    {
        rank: 67,
        title: 'Jailhouse Rock',
        artist: 'Elvis Presley',
        album: 'Elvis 30 #1 Hits',
        year: '1957'
    },
    {
        rank: 68,
        title: 'Tangled Up in Blue',
        artist: 'Bob Dylan',
        album: 'Blood on the Tracks',
        year: '1975'
    },
    {
        rank: 69,
        title: 'Crying',
        artist: 'Roy Orbison',
        album: 'For the Lonely: 18 Greatest Hits',
        year: '1961'
    },
    {
        rank: 70,
        title: 'Walk On By',
        artist: 'Dionne Warwick',
        album: 'The Dionne Warwick Collection: Her All-Time Greatest Hits',
        year: '1964'
    },
    {
        rank: 71,
        title: "Papa's Got a Brand New Bag",
        artist: 'James Brown',
        album: '50th Anniversary Collection',
        year: '1966'
    },
    {
        rank: 72,
        title: 'California Girls',
        artist: 'The Beach Boys',
        album: 'Sounds of Summer: The Very Best of the Beach Boys',
        year: '1965'
    },
    {
        rank: 73,
        title: 'Superstition',
        artist: 'Stevie Wonder',
        album: 'Talking Book',
        year: '1973'
    },
    {
        rank: 74,
        title: 'Summertime Blues',
        artist: 'Eddie Cochran',
        album: "Somethin' Else",
        year: '1958'
    },
    {
        rank: 75,
        title: 'Whole Lotta Love',
        artist: 'Led Zeppelin',
        album: 'Led Zeppelin II',
        year: '1969'
    },
    {
        rank: 76,
        title: 'Strawberry Fields Forever',
        artist: 'The Beatles',
        album: 'Magical Mystery Tour',
        year: '1967'
    },
    {
        rank: 77,
        title: 'Mystery Train',
        artist: 'Elvis Presley',
        album: 'Sunrise',
        year: '1955'
    },
    {
        rank: 78,
        title: 'I Got You (I Feel Good)',
        artist: 'James Brown',
        album: 'James Brown 50th Anniversary Collection',
        year: '1966'
    },
    {
        rank: 79,
        title: 'Mr. Tambourine Man',
        artist: 'The Byrds',
        album: 'Mr. Tambourine Man',
        year: '1965'
    },
    {
        rank: 80,
        title: 'You Really Got Me',
        artist: 'The Kinks',
        album: 'Kinks',
        year: '1964'
    },
    {
        rank: 81,
        title: 'I Heard It Through the Grapevine',
        artist: 'Marvin Gaye',
        album: 'Every Motown Hit',
        year: '1968'
    },
    {
        rank: 82,
        title: 'Blueberry Hill',
        artist: 'Fats Domino',
        album: 'The Fats Domino Jukebox',
        year: '1956'
    },
    {
        rank: 83,
        title: 'Norwegian Wood (This Bird Has Flown)',
        artist: 'The Beatles',
        album: 'Rubber Soul',
        year: '1965'
    },
    {
        rank: 84,
        title: 'Every Breath You Take',
        artist: 'The Police',
        album: 'Synchronicity',
        year: '1983'
    },
    {
        rank: 85,
        title: 'Crazy',
        artist: 'Patsy Cline',
        album: "Patsy Cline's Greatest Hits",
        year: '1961'
    },
    {
        rank: 86,
        title: 'Thunder Road',
        artist: 'Bruce Springsteen',
        album: 'Born to Run',
        year: '1975'
    },
    {
        rank: 87,
        title: 'Ring of Fire',
        artist: 'Johnny Cash',
        album: 'The Man in Black: His Greatest Hits',
        year: '1963'
    },
    {
        rank: 88,
        title: 'My Girl',
        artist: 'The Temptations',
        album: 'The Temptations Sing Smokey',
        year: '1965'
    },
    {
        rank: 89,
        title: "California Dreamin'",
        artist: 'The Mamas & The Papas',
        album: 'If You Can Believe Your Eyes And Ears',
        year: '1965'
    },
    {
        rank: 90,
        title: 'In The Still Of The Nite',
        artist: 'The Five Satins',
        album: 'The Five Satins: Their Greatest Hits',
        year: '1956'
    },
    {
        rank: 91,
        title: 'Suspicious Minds',
        artist: 'Elvis Presley',
        album: 'Elvis 30 #1 Hits',
        year: '1969'
    },
    {
        rank: 92,
        title: 'Blitzkrieg Bop',
        artist: 'Ramones',
        album: 'Ramones',
        year: '1976'
    },
    {
        rank: 93,
        title: "I Still Haven't Found What I'm Looking For",
        artist: 'U2',
        album: 'The Joshua Tree',
        year: '1987'
    },
    {
        rank: 94,
        title: 'Good Golly',
        artist: 'Little Richard',
        album: 'The Georgia Peach',
        year: '1958'
    },
    {
        rank: 95,
        title: 'Blue Suede Shoes',
        artist: 'Carl Perkins',
        album: 'Original Sun Greatest Hits',
        year: '1956'
    },
    {
        rank: 96,
        title: 'Great Balls of Fire',
        artist: 'Jerry Lee Lewis',
        album: 'Original Sun Greatest Hits',
        year: '1957'
    },
    {
        rank: 97,
        title: 'Roll Over Beethoven',
        artist: 'Chuck Berry',
        album: 'The Anthology',
        year: '1956'
    },
    {
        rank: 98,
        title: 'Love And Happiness',
        artist: 'Al Green',
        album: "I'm Still in Love With You",
        year: '1972'
    },
    {
        rank: 99,
        title: 'Fortunate Son',
        artist: 'Creedence Clearwater Revival',
        album: 'Willy And The Poor Boys',
        year: '1970'
    },
    {
        rank: 100,
        title: 'Crazy',
        artist: 'Gnarls Barkley',
        album: 'St. Elsewhere',
        year: '2006'
    }
]

export function gen() {
    const response: Wrestler[] = []
    const songz = shuffleArray(songs)
    const movez = shuffleArray(moves)
    const nickz = shuffleArray(nickNames)

    for (let i = 0; i < 100; i++) {
        const firstName = getRandomElement(usNames)
        const surName = getRandomElement(surNames)

        const wrestler: Wrestler = {
            id: hasher.encode(i),
            name: `${firstName.name} ${surName.name}`,
            nickName: nickz[i],
            catchPhrase: prases[i],
            entranceMusic: songz[i].title,
            finisherMove: movez[i]
        }

        response.push(wrestler)
    }

    return response
}

function getRandomElement<T>(items: ReadonlyArray<T>): T {
    return items[Math.floor(Math.random() * items.length)]
}

function shuffleArray<T>(array: T[]): T[] {
    const result = [...array]
    for (let i = result.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        ;[result[i], result[j]] = [result[j], result[i]]
    }
    return result
}
